USE [master]
GO

/****** Object:  Database [db_pressnews]    Script Date: 15/04/2019 07:55:16 ******/
CREATE DATABASE [db_pressnews]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_pressnews', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\db_pressnews.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_pressnews_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\db_pressnews_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [db_pressnews] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_pressnews].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_pressnews] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_pressnews] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_pressnews] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_pressnews] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_pressnews] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_pressnews] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [db_pressnews] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_pressnews] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_pressnews] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_pressnews] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_pressnews] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_pressnews] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_pressnews] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_pressnews] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_pressnews] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_pressnews] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_pressnews] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_pressnews] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_pressnews] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_pressnews] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_pressnews] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_pressnews] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_pressnews] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_pressnews] SET  MULTI_USER 
GO

ALTER DATABASE [db_pressnews] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_pressnews] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_pressnews] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_pressnews] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_pressnews] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_pressnews] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_pressnews] SET  READ_WRITE 
GO


