//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressNews.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_pressnewsEntities1 : DbContext
    {
        public db_pressnewsEntities1()
            : base("name=db_pressnewsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
        public virtual DbSet<TB_CATEGORIES> TB_CATEGORIES { get; set; }
        public virtual DbSet<TB_NEWS> TB_NEWS { get; set; }
    }
}
