//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressNews.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NEWS
    {
        public int id_new { get; set; }
        public string nm_new { get; set; }
        public string ds_txtnew { get; set; }
        public string ds_urlnew { get; set; }
        public System.DateTime dt_new { get; set; }
        public System.DateTime dt_icl { get; set; }
        public int cd_usricl { get; set; }
        public Nullable<System.DateTime> dt_alt { get; set; }
        public Nullable<int> cd_usralt { get; set; }
        public Nullable<int> id_cat { get; set; }
    
        public virtual TB_CATEGORIES TB_CATEGORIES { get; set; }
    }
}
