//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressNews.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public int id_usr { get; set; }
        public string nm_lgnusr { get; set; }
        public string ds_emlusr { get; set; }
        public string ds_pwdusr { get; set; }
        public string nm_usr { get; set; }
        public System.DateTime dt_icl { get; set; }
    }
}
